import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { projectForSession } from '../projects.ts';
import { randomUUID } from 'node:crypto';
import { loadPrompt, render, sessionLogDir } from '../util/render.ts';
import { parseStructured, strictParse } from '../llm/structured.ts';
import { runClaude } from '../llm/runClaude.ts';
import { refresh, assertFresh } from './repoFreshness.ts';
import { anchorCheck } from './repoAnchor.ts';
import { loadPrdTruth } from './prdTruth.ts';
import { GateBSchema, GATE_B_CONTRACT } from './envelopes.ts';
import type { GateBEnvelope, Verdict } from './envelopes.ts';
import { loadConfig } from '../config.ts';
import { log } from '../util/log.ts';
import { store } from '../store/index.ts';
const { patch, appendEvent } = store; // take the local implementation methods through the SessionStore seam (free functions have no `this`, so destructuring is safe)
import { projectActions } from '../project/index.ts';
import { acceptanceMarkdown } from '../util/acceptance.ts';
import type { Session } from '../types.ts';

export function gateBPaths(id: string): { draft: string; issues: string } {
  const dir = sessionLogDir(id);
  return { draft: resolve(dir, 'gate-b.json'), issues: resolve(dir, 'issues.json') };
}

export async function persistGateB(s: Session, env: GateBEnvelope): Promise<void> {
  const { draft, issues } = gateBPaths(s.id);
  writeFileSync(draft, JSON.stringify(env, null, 2));
  writeFileSync(issues, JSON.stringify(env.issue_specs, null, 2));
  await patch(s.id, { gate_b_draft_path: draft, issue_specs_path: issues });
}

function appendTechDesignMachine(deliveryDir: string, slug: string, env: GateBEnvelope): void {
  const doc = resolve(deliveryDir, slug, 'tech-design.md');
  if (!existsSync(doc)) return;
  const kd = Object.entries(env.key_decisions ?? {})
    .map(([k, v]) => `- **${k}**: ${typeof v === 'string' ? v : JSON.stringify(v)}`)
    .join('\n');
  const acc = acceptanceMarkdown(env.acceptance);
  const block =
    `\n\n---\n\n## 🤖 Machine tech design (codex-reviews / claude-revises, final draft · pending a human check and trim)\n` +
    `> Generated by \`claude -p\` and finalised after several rounds of codex adversarial re-review. A human checks it and gives GO from it; it does not replace the "⚡ Key decisions" section above (please move the important points up there).\n\n` +
    `### Key decisions (machine draft)\n${kd || '(none)'}\n\n` +
    `### Acceptance contract (outer loop · all of it should be red right now)\n${acc || '(none)'}\n\n` +
    `### Design body\n${env.tech_design_markdown || '(none)'}\n`;
  appendFileSync(doc, block);
}

// Findings the adversarial loop hit its cap without resolving are appended to tech-design.md (that document is
// exactly what a human reviews before giving GO).
export function appendResidualToDoc(
  deliveryDir: string,
  slug: string,
  r: { round: number; used: string; findings: Verdict['findings'] },
): void {
  const doc = resolve(deliveryDir, slug, 'tech-design.md');
  if (!existsSync(doc)) return;
  const items = r.findings
    .map(
      (f, i) =>
        `${i + 1}. **[${f.severity}]** ${f.issue}${f.where ? ` (where: ${f.where})` : ''}\n` +
        `   - Suggestion: ${f.fix || '(none)'}${f.evidence ? `\n   - Evidence: ${f.evidence}` : ''}`,
    )
    .join('\n');
  const block =
    `\n\n---\n\n## ⚖️ Unarbitrated adversarial-review findings (human arbitration required)\n` +
    `> The codex/claude adversarial re-review hit its cap at round ${r.round} (reviewer=${r.used}), and the design still does not resolve the ${r.findings.length} finding(s) below. ` +
    `**A human must arbitrate each one before GO**: accept it and change the design, or reject it and record why.\n\n${items}\n`;
  appendFileSync(doc, block);
}

// Once the Gate B loop terminates, write "the final design + any unarbitrated residue" into tech-design.md in
// one go (that document is what a human reviews before GO).
// It waits until the loop ends so that a round does not append another draft each time; the draft JSON
// (gate-b.json) is updated in place every round instead.
export function finalizeGateBDoc(s: Session): void {
  const { draft } = gateBPaths(s.id);
  if (!existsSync(draft)) return;
  let env: GateBEnvelope;
  try {
    env = GateBSchema.parse(JSON.parse(readFileSync(draft, 'utf8')));
  } catch {
    return;
  }
  const deliveryDir = projectForSession(s).deliveryDir;
  appendTechDesignMachine(deliveryDir, s.slug, env);
  if (s.adversarial_residual) {
    try {
      const r = JSON.parse(s.adversarial_residual) as { round: number; used: string; findings: Verdict['findings'] };
      appendResidualToDoc(deliveryDir, s.slug, r);
    } catch {
      /* ignore */
    }
  }
}

// Run one Gate B step: analyse -> parse -> scaffold the tech-design document + write the issue drafts. Throws
// on failure.
export async function runGateB(s: Session): Promise<GateBEnvelope> {
  const proj = projectForSession(s);
  // The single requirement input: the PRD source of truth synthesised mechanically when Gate A sealed (source
  // text + review final draft + PM confirmations). If it is missing it is synthesised on the spot as a
  // fallback (see prdTruth.ts).
  const prdTruth = loadPrdTruth(s);
  const fresh = await refresh(s.branch, proj);
  assertFresh(fresh); // Gate B works against a freshly fetched source of truth in the code too -> if it cannot be fetched, park rather than silently degrade
  // Checkout anchor check: claude reads the live checkout, so if that is off the anchored sha or the tree is
  // dirty, either disclose it to the model (warn) or park (block).
  const { off, disclosure } = anchorCheck(proj, fresh, loadConfig().runtime.gates?.checkout_anchor ?? 'warn');
  if (off.length) {
    log.warn(`Gate B: the ${off.join(', ')} checkout is not anchored to origin/${s.branch} (disclosed in the prompt; continuing to produce a design)`);
    await appendEvent(s.id, 'checkout_off_anchor', { gate: 'B', off, branch: s.branch });
  }
  const freshnessBlock = render(loadPrompt('partials/repo-freshness.md', proj.id), {
    FETCHED_AT: fresh.fetchedAt,
    REPO_REFS: fresh.refsText + disclosure,
  });
  const prompt = render(loadPrompt('gate-b.md', proj.id), {
    REPO_FRESHNESS: freshnessBlock,
    SLUG: s.slug,
    PRD_TRUTH: prdTruth,
  });

  const dir = sessionLogDir(s.id);
  writeFileSync(resolve(dir, 'gate-b.prompt.txt'), prompt);
  const sid = randomUUID(); // pin the session id: on a parse failure, resume the same session to feed the error back and re-emit (used only within this call)
  const res = await runClaude(prompt, { label: 'Gate B', sessionId: sid, cwd: proj.root });
  writeFileSync(resolve(dir, 'gate-b.raw.txt'), res.raw ?? '');
  if (!res.ok) throw new Error(`Gate B claude failed: ${res.error}`);

  let env: GateBEnvelope;
  try {
    env = await parseStructured<GateBEnvelope>({
      text: res.result,
      parse: (t) => strictParse(GateBSchema, t),
      reEmit: async (instruction) => {
        const r = await runClaude(instruction, { label: 'Gate B · repair the output', resume: sid, cwd: proj.root });
        return r.ok ? r.result : null;
      },
      buildRepairInstruction: (error) =>
        render(loadPrompt('partials/parse-repair.md', proj.id), { ERROR: error, CONTRACT: GATE_B_CONTRACT }),
      maxRetries: loadConfig().runtime.parse_repair_retries ?? 2,
      note: (kind, detail) => appendEvent(s.id, `gateb_${kind}`, detail),
      dump: (raw) => {
        try { writeFileSync(resolve(dir, 'gate-b.result.txt'), raw); } catch { /* a failed dump must not block the flow */ }
      },
    });
  } catch (e) {
    writeFileSync(resolve(dir, 'gate-b.result.txt'), res.result);
    throw new Error(`Gate B output failed to parse (the self-healing retries did not recover it): ${String(e).slice(0, 200)} (see logs/${s.id}/gate-b.result.txt)`);
  }

  await patch(s.id, {
    repo_shas_b: JSON.stringify(fresh.shas),
    gate_b_cost_usd: res.costUsd,
  });
  await persistGateB(s, env);

  await projectActions(proj).scaffoldTechDesign({
    slug: s.slug,
    prd: s.prd_url,
    owner: env.issue_specs[0]?.assignee ?? undefined, // note: scaffold's --owner = the document owner (an assignee login), not a GitHub org
    title: s.title,
    force: true,
  });
  // Note: the machine design body is not appended here — finalizeGateBDoc writes it in one go once the
  // codex-reviews / claude-revises loop has settled (which avoids piling up a draft per round).
  return env;
}
