// The Worker's bindings, as wrangler.jsonc declares them for the `dev` and `prod` environments.
//
// Written by hand rather than generated by `wrangler types`: the generated file also carries the whole
// runtime API (tens of thousands of lines) and would have to be regenerated on every wrangler bump. The
// runtime types come from @cloudflare/workers-types instead; this file is just the bindings, and
// test/config.test.ts pins the vars wrangler.jsonc sets to exactly the two below.
import type { DeviceHub } from './hub.ts';

export interface Env {
  // 'dev' or 'prod'. Read only through environmentOf() below; any other value -- including a missing one --
  // comes out as null, which every caller treats as "refuse" (the fail-closed direction).
  FORGELINE_ENV?: string;
  // Kill switch (docs/cloud-agent.md section 10.3): jobs are created only when this is exactly "true".
  FORGELINE_JOBS_ENABLED?: string;
  DB: D1Database;
  DEVICE_HUB: DurableObjectNamespace<DeviceHub>;
}

export const ENVIRONMENTS = ['dev', 'prod'] as const;
export type Environment = (typeof ENVIRONMENTS)[number];

// The environment name, or null when it is missing or unknown. Callers must treat null as "refuse".
export function environmentOf(env: Pick<Env, 'FORGELINE_ENV'>): Environment | null {
  const v = env.FORGELINE_ENV;
  return v === 'dev' || v === 'prod' ? v : null;
}
