// The nativeGithub adapter — it implements ProjectActions by calling the gh CLI directly, **depending
// neither on scripts in the target project nor on the demo adapter** (which is why it imports only
// proc.run — avoiding the "a test mocks workspace.ts, leaves out an export, and it explodes at import time"
// fragility).
// It is for an open-source project, or any project with no forge script conventions (proj.actions='native').
// The selection point is in ./index.ts.
//
// What it covers (stated honestly):
//   · **A single repo works end to end**: scaffoldReview and scaffoldTechDesign generate the delivery
//     documents (including `status: draft`, which the gates append to and markReviewActive flips to active);
//     createSingle maps the short code to a real repo name through repoMap and calls gh for real; addLabel
//     and listEpicChildren call gh for real; approve and publish have no equivalent on plain GitHub (there is
//     no project status field, and design documents are not published to a main repo), so they are no-ops
//     that return ok.
//   · **A multi-repo Epic (createEpic) works end to end**: the Epic itself is created in the umbrella repo
//     and each sub-issue in its code repo, all carrying the epic:<slug> label (which is how listEpicChildren
//     rediscovers them on a retry), and all returned in the **local repo key** namespace (matching doWrites's
//     coverage check and the size labelling; the adapter translates to a slug at the gh boundary). The
//     simplification: a sub-issue carries only its title, labels and DRI, and the whole requirement's
//     outer-ring acceptance goes in the Epic's body.
// The namespace contract: the CreatedIssue.repo returned by createSingle and createEpic is always the
// **local repo key** (under demo the key is the slug, so nothing changes; in a monorepo the key '.' is not
// the slug 'your-monorepo') — doWrites reasons in keys and letters throughout, and addLabel and
// listEpicChildren take a key and translate it to a slug themselves.
// The follow-up work is in docs/architecture-control-plane-split.md 0.2c.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { run } from '../util/proc.ts';
import type { ProjectActions, ScriptResult } from './actions.ts';
import type { ProjectFull } from '../projects.ts';
import type { CreatedIssue } from '../types.ts';
import type { ScaffoldOpts } from '../workspace.ts';

const TIMEOUT_MS = 60000;

function escRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
// Parse the issue URLs out of gh issue create's output (deduplicated).
function parseIssueUrls(stdout: string, owner: string): CreatedIssue[] {
  const re = new RegExp(`https://github\\.com/${escRe(owner)}/([\\w.-]+)/issues/(\\d+)`, 'g');
  const seen = new Set<string>();
  const out: CreatedIssue[] = [];
  for (const m of stdout.matchAll(re)) {
    const key = `${m[1]}#${m[2]}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ repo: m[1], number: Number(m[2]), url: m[0] });
  }
  return out;
}

// The delivery document's front matter. The `status: draft` line is a convention the gates rely on:
// markReviewActive rewrites it to active with /^status: draft.*$/.
function frontMatter(o: ScaffoldOpts): string {
  const fm = [`slug: ${o.slug}`, `title: ${o.title ?? o.slug}`, 'status: draft           # the service sets this to active once the gate passes'];
  if (o.owner) fm.push(`owner: ${o.owner}`);
  if (o.prd) fm.push(`prd: ${o.prd}`);
  return `---\n${fm.join('\n')}\n---\n`;
}
function reqReviewDoc(o: ScaffoldOpts): string {
  return `${frontMatter(o)}\n# ${o.title ?? o.slug} · requirement review\n\n> Generated by forge's nativeGithub adapter (no project scripts). The machine review's output is appended below (🤖 machine review output).\n${o.prd ? `\n## PRD\n${o.prd}\n` : ''}`;
}
function techDesignDoc(o: ScaffoldOpts): string {
  return `${frontMatter(o)}\n# ${o.title ?? o.slug} · technical plan\n\n> Generated by forge's nativeGithub adapter (no project scripts). The machine's technical plan is appended below.\n`;
}

export function makeNativeGithubActions(proj: ProjectFull): ProjectActions {
  const { owner, repoMap, repoSlugs, deliveryDir, umbrella } = proj;
  // Short code (C/U/A, Gate B's contract) -> local repo key (repoMap); under demo the key is the repo name.
  // Anything missing passes through unchanged.
  const localOf = (repo: string): string => repoMap[repo] ?? repo;
  // Local repo key -> GitHub slug (repoSlugs); a monorepo's '.' becomes 'your-monorepo'. Anything missing
  // passes through unchanged (under demo the repo name is the slug).
  const slugOf = (local: string): string => repoSlugs[local] ?? local;
  // Generate the delivery document, non-destructively: an existing one is kept, so the gates' appended
  // sections, anyone's edits, and an already-active status are never overwritten. A dry run writes nothing.
  const scaffold = (o: ScaffoldOpts, file: string, render: (o: ScaffoldOpts) => string): ScriptResult => {
    if (o.dryRun) return { ok: true, stdout: `(dry-run) native scaffold ${file}`, stderr: '' };
    const dir = resolve(deliveryDir, o.slug);
    mkdirSync(dir, { recursive: true });
    const doc = resolve(dir, file);
    const created = !existsSync(doc);
    if (created) writeFileSync(doc, render(o));
    return { ok: true, stdout: `native scaffold ${file}: ${created ? 'created' : 'already exists, skipped'}`, stderr: '' };
  };
  // Plain GitHub has no project status field and does not publish design documents to a main repo, so approve
  // and publish do nothing on the native path — a no-op returning ok, not a failure.
  const noop = (note: string): Promise<{ ok: boolean; stdout: string; stderr: string }> => Promise.resolve({ ok: true, stdout: `native no-op: ${note}`, stderr: '' });
  // Create one issue (gh issue create -R owner/<slug>): parse out the number and url, and set repo to the
  // **local key** (the namespace contract).
  const createIssue = async (
    local: string,
    title: string,
    o: { labels?: (string | null | undefined)[]; assignee?: string | null; body?: string | null },
  ): Promise<{ ok: boolean; issue: CreatedIssue | null; stdout: string; stderr: string }> => {
    const args = ['issue', 'create', '-R', `${owner}/${slugOf(local)}`, '--title', title, '--body', o.body ?? ''];
    for (const l of (o.labels ?? []).filter((x): x is string => !!x)) args.push('--label', l);
    if (o.assignee) args.push('--assignee', o.assignee);
    const r = await run('gh', args, { timeoutMs: TIMEOUT_MS });
    const ok = r.code === 0 && !r.timedOut;
    const parsed = ok ? parseIssueUrls(r.stdout, owner)[0] : undefined;
    const issue = parsed ? { repo: local, number: parsed.number, url: parsed.url } : null;
    return { ok: ok && !!issue, issue, stdout: r.stdout, stderr: r.stderr };
  };
  return {
    scaffoldReview: (o) => Promise.resolve(scaffold(o, 'req-review.md', reqReviewDoc)),
    scaffoldTechDesign: (o) => Promise.resolve(scaffold(o, 'tech-design.md', techDesignDoc)),
    approveTechDesign: () => noop('plain GitHub has no project status field; once the issue exists it is delivered'),
    // published:false — the native path opens no real PR, so the DONE wording does not falsely claim it was merged automatically.
    publishTechDesign: () => Promise.resolve({ ok: true, stdout: 'native no-op: plain GitHub does not publish design documents to a main repo', stderr: '', published: false }),
    createSingle: async (repo, title, o) => {
      // type, prio and area map onto ordinary GitHub labels; status (the project status field) has no
      // equivalent on the native path and is skipped.
      const local = localOf(repo);
      if (o.dryRun) return { ok: true, stdout: `(dry-run) gh issue create -R ${owner}/${slugOf(local)} ${title}`, stderr: '', issues: [] };
      const r = await createIssue(local, title, { labels: [o.type, o.prio, o.area], assignee: o.assignee, body: o.body });
      return { ok: r.ok, stdout: r.stdout, stderr: r.stderr, issues: r.issue ? [r.issue] : [] };
    },
    // A multi-repo Epic: the Epic itself goes in the umbrella repo and each sub-issue in its code repo, all
    // carrying epic:<slug> (which is how a retry rediscovers them through listEpicChildren) and the DRI.
    // The whole requirement's outer-ring acceptance goes in the Epic's body (o.body); a sub-issue carries only
    // its title (the simplification). Any creation failing gives ok=false — the failure is never silent, and
    // doWrites moves to WRITE_FAILED.
    createEpic: async (slug, title, children, o) => {
      const epicLabel = `epic:${slug}`;
      if (o.dryRun) {
        const lines = [
          `(dry-run) gh issue create -R ${owner}/${slugOf(umbrella)} [Epic] ${title}`,
          ...children.map((c) => `(dry-run) gh issue create -R ${owner}/${slugOf(localOf(c.repo))} [child] ${c.title}`),
        ];
        return { ok: true, stdout: lines.join('\n'), stderr: '', issues: [] };
      }
      const issues: CreatedIssue[] = [];
      const errs: string[] = [];
      const ep = await createIssue(umbrella, title, { labels: [epicLabel, o.type], assignee: o.assignee, body: o.body });
      if (ep.issue) issues.push(ep.issue);
      else errs.push(`Epic(${umbrella}): ${(ep.stderr || ep.stdout || 'gh returned no URL').slice(0, 120)}`);
      for (const c of children) {
        const cl = localOf(c.repo);
        const ci = await createIssue(cl, c.title, { labels: [epicLabel, o.type], assignee: o.assignee });
        if (ci.issue) issues.push(ci.issue);
        else errs.push(`child(${cl}): ${(ci.stderr || ci.stdout || 'gh returned no URL').slice(0, 120)}`);
      }
      const ok = errs.length === 0;
      const stdout = issues.map((i) => `✓ ${i.repo}#${i.number} ${i.url}`).join('\n');
      return { ok, stdout, stderr: ok ? '' : errs.join('; '), issues };
    },
    addLabel: async (repo, num, label) => {
      // repo arrives as the **local key** (doWrites's namespace), so it is translated to a slug before
      // building gh -R.
      const r = await run('gh', ['issue', 'edit', String(num), '-R', `${owner}/${slugOf(repo)}`, '--add-label', label], { timeoutMs: TIMEOUT_MS });
      return { ok: r.code === 0 && !r.timedOut, stderr: r.stderr };
    },
    listEpicChildren: async (repo, slug) => {
      // repo arrives as the **local key** and becomes a slug for gh -R; the issue.repo returned is set back to
      // the local key (the namespace contract, which doWrites's coverage check depends on).
      const r = await run('gh', ['issue', 'list', '-R', `${owner}/${slugOf(repo)}`, '-l', `epic:${slug}`, '--state', 'all', '--json', 'number,url'], { timeoutMs: TIMEOUT_MS });
      if (r.code !== 0 || r.timedOut) return { ok: false, issues: [], stderr: r.stderr || `exit ${r.code}` };
      try {
        const arr = JSON.parse(r.stdout || '[]') as { number?: number; url?: string }[];
        const issues = arr
          .filter((a) => typeof a.number === 'number' && typeof a.url === 'string')
          .map((a) => ({ repo, number: a.number as number, url: a.url as string }));
        return { ok: true, issues, stderr: '' };
      } catch {
        return { ok: false, issues: [], stderr: "gh issue list --json could not be parsed" };
      }
    },
  };
}
