//! The contract: fixtures/wire/v1/ (generated by tools/wire-fixtures.ts, never hand-edited). This crate is the third
//! implementation held to these files, after the reference and the Worker. If a case here fails, either this code
//! is wrong or the fixture is -- and a wrong fixture is reported, never worked around in this crate.

mod common;

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use common::{
    FIXTURES, Fixture, device_id, fixture, fixtures, hex, key, key_by_kid, keyring, keys,
};
use forgeline_agent::wire::json::{self, Json};
use forgeline_agent::wire::{Body, Draft, Keyring, RejectCode, Verifier, kid_of, seal};

fn verifier_for(f: &Fixture) -> Verifier {
    let mut ring = Keyring::default();
    for kid in &f.trust {
        let k = key_by_kid(kid).unwrap_or_else(|| panic!("trusted kid {kid} is not in keys.json"));
        ring.add(
            k.owner.as_deref().expect("a trusted key has an owner"),
            &k.public_bytes(),
        )
        .unwrap();
    }
    Verifier::new(&f.receiver, ring)
}

fn verdicts(f: &Fixture) -> Vec<String> {
    let mut v = verifier_for(f);
    f.frames
        .iter()
        .map(|raw| {
            v.verify(raw, f.now)
                .map_or_else(|r| r.code.as_str().to_string(), |_| "ok".into())
        })
        .collect()
}

#[test]
fn every_fixture_frame_gets_exactly_the_stated_verdict() {
    let all = fixtures();
    // A floor, so a fixture directory that lost files (or a wrong path) cannot pass by checking fewer frames.
    assert!(
        all.len() >= 38,
        "only {} fixture files found under {FIXTURES}",
        all.len()
    );
    for must in [
        "reject-oversized",
        "reject-sig-padding-bits",
        "order-stale-before-replay",
    ] {
        assert!(
            all.iter().any(|(n, _)| n == must),
            "fixture {must} is missing"
        );
    }
    let mut wrong = Vec::new();
    for (name, f) in &all {
        assert_eq!(f.frames.len(), f.expect.len(), "{name}");
        let got = verdicts(f);
        if got != f.expect {
            wrong.push(format!("{name}: expected {:?}, got {:?}", f.expect, got));
        }
    }
    assert!(wrong.is_empty(), "\n{}", wrong.join("\n"));
}

#[test]
fn the_fixtures_cover_every_code_and_every_message_type() {
    let all = fixtures();
    let expected: BTreeSet<&str> = all
        .iter()
        .flat_map(|(_, f)| f.expect.iter().map(String::as_str))
        .collect();
    for code in RejectCode::ALL {
        assert!(
            expected.contains(code.as_str()),
            "no fixture is rejected with {}",
            code.as_str()
        );
    }
    let mut types = BTreeSet::new();
    for (_, f) in &all {
        for (raw, verdict) in f.frames.iter().zip(&f.expect) {
            if verdict == "ok" {
                types.insert(
                    serde_json::from_str::<serde_json::Value>(raw).unwrap()["type"]
                        .as_str()
                        .unwrap()
                        .to_string(),
                );
            }
        }
    }
    assert_eq!(
        types.into_iter().collect::<Vec<_>>(),
        [
            "ack",
            "auth",
            "challenge",
            "error",
            "event",
            "job",
            "result",
            "welcome"
        ]
    );
}

#[test]
fn the_test_keys_are_the_rfc8032_vectors_and_their_kids_are_derived() {
    let rfc = [
        (
            "cloud",
            "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
        ),
        (
            "device",
            "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
        ),
        (
            "attacker",
            "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
        ),
    ];
    assert_eq!(keys().len(), rfc.len());
    for (name, public_hex) in rfc {
        let k = key(name);
        assert_eq!(
            k.public_bytes().to_vec(),
            hex(public_hex),
            "{name}: public key"
        );
        assert_eq!(
            k.signing().verifying_key().to_bytes(),
            k.public_bytes(),
            "{name}: the seed yields the public key"
        );
        assert_eq!(kid_of(&k.public_bytes()), k.kid, "{name}: kid");
    }
}

/// Rebuild an accepted frame from its parts and seal it again with the key its kid names. Ed25519 is deterministic,
/// so the same key over the same canonical bytes must give the same signature -- and the same frame text, to the
/// byte. This exercises the sending side (draft -> canonical form -> signature -> frame), which the verdict test
/// above does not.
fn reseal(raw: &str) -> Option<(String, String)> {
    let v: serde_json::Value = serde_json::from_str(raw).unwrap();
    let k = key_by_kid(v["kid"].as_str()?)?;
    let draft = Draft {
        kind: v["type"].as_str()?.into(),
        id: v["id"].as_str()?.into(),
        ts: v["ts"].as_i64()?,
        from: v["from"].as_str()?.into(),
        to: v["to"].as_str()?.into(),
        re: v.get("re").and_then(|r| r.as_str()).map(str::to_string),
        body: v["body"].as_object()?.clone(),
    };
    let frame = seal(&draft, &k.signing()).unwrap();
    Some((k.name, frame))
}

#[test]
fn signing_reproduces_every_accepted_fixture_frame_byte_for_byte() {
    let mut by_device = 0;
    let mut by_cloud = 0;
    for (name, f) in fixtures() {
        for (raw, verdict) in f.frames.iter().zip(&f.expect) {
            // Only frames that are canonical and honestly signed by the key they name can be reproduced; the
            // rejection fixtures are deliberately neither.
            if verdict != "ok" {
                continue;
            }
            let (signer, again) =
                reseal(raw).unwrap_or_else(|| panic!("{name}: cannot rebuild the frame"));
            assert_eq!(&again, raw, "{name}: resealed with the {signer} key");
            match signer.as_str() {
                "device" => by_device += 1,
                "cloud" => by_cloud += 1,
                other => panic!("{name}: an accepted frame signed by {other}"),
            }
        }
    }
    // auth, event, ack-job, result-done, result-rejected
    assert!(
        by_device >= 5,
        "only {by_device} device-signed frames reproduced"
    );
    assert!(
        by_cloud >= 8,
        "only {by_cloud} cloud-signed frames reproduced"
    );
}

#[derive(serde::Deserialize)]
struct CanonicalCase {
    about: String,
    input: String,
    canonical: Option<String>,
    #[serde(default)]
    error: bool,
}

#[test]
fn canonical_json_cases() {
    let text = fs::read_to_string(Path::new(FIXTURES).join("canonical.json")).unwrap();
    let cases: Vec<CanonicalCase> = serde_json::from_value(
        serde_json::from_str::<serde_json::Value>(&text).unwrap()["cases"].clone(),
    )
    .unwrap();
    assert!(cases.len() >= 10);
    for c in cases {
        let got = json::parse(&c.input).and_then(|v| json::canonicalize(&v));
        if c.error {
            assert!(got.is_err(), "{}: should be refused, got {got:?}", c.about);
            continue;
        }
        let want = c.canonical.unwrap();
        assert_eq!(got.as_deref(), Ok(want.as_str()), "{}", c.about);
        // A canonical form is a fixed point.
        assert_eq!(
            json::canonicalize(&json::parse(&want).unwrap()).as_deref(),
            Ok(want.as_str()),
            "{} (fixed point)",
            c.about
        );
        // The sending side builds bodies as serde_json values; they must canonicalise identically.
        let via_serde = Json::from_value(&serde_json::from_str(&c.input).unwrap());
        assert_eq!(
            json::canonicalize(&via_serde).as_deref(),
            Ok(want.as_str()),
            "{} (via serde_json)",
            c.about
        );
    }
}

#[test]
fn flipping_one_signature_bit_is_caught() {
    let f = fixture("job-session-reply");
    let raw = &f.frames[0];
    let v: serde_json::Value = serde_json::from_str(raw).unwrap();
    let sig = v["sig"].as_str().unwrap();
    let mut bytes = forgeline_agent::b64::decode(sig).unwrap();
    bytes[0] ^= 1;
    let flipped = raw.replace(sig, &forgeline_agent::b64::encode(&bytes));
    let mut verifier = verifier_for(&f);
    assert_eq!(
        verifier.verify(&flipped, f.now).unwrap_err().code,
        RejectCode::BadSignature
    );
}

// ---- Edge cases outside the fixtures --------------------------------------------------------------------------
//
// Each expectation below was obtained by running the reference verifier (tools/wire-fixtures.ts, verifyFrame) on the
// same frame on 2026-10-03. They pin the places where a straightforward Rust implementation (serde_json, a strict
// base64 decoder) would disagree with the reference about *which* code a bad frame gets. They are candidates for
// the golden fixtures (reported as doc feedback), which is where they belong: all three implementations should be
// held to them, not only this one.

const NOW: i64 = 1_791_072_000_000;

/// A cloud-signed job to this device whose body is `{"a":1}`, so replacing `"a":1` swaps in any body value.
fn base_frame() -> String {
    let mut body = Body::new();
    body.insert("a".into(), 1.into());
    let draft = Draft {
        kind: "job".into(),
        id: "01M423BN0RBT69J0H0FBXEPW90".into(),
        ts: NOW - 1000,
        from: "cloud".into(),
        to: device_id(),
        re: None,
        body,
    };
    seal(&draft, &key("cloud").signing()).unwrap()
}

fn verdict(raw: &str) -> String {
    let mut v = Verifier::new(&device_id(), keyring(&["cloud"]));
    v.verify(raw, NOW)
        .map_or_else(|r| r.code.as_str().to_string(), |_| "ok".into())
}

#[test]
fn edge_cases_agree_with_the_reference() {
    let good = base_frame();
    assert_eq!(verdict(&good), "ok");
    let ts = format!("\"ts\":{}", NOW - 1000);
    let r = |from: &str, to: &str| good.replacen(from, to, 1);
    let cases: Vec<(&str, String, &str)> = vec![
        // The version is read before anything else is judged: JSON.parse accepts these bodies, so v=2 wins.
        (
            "v=2 with a lone surrogate in the body",
            r("\"v\":1", "\"v\":2").replacen("\"a\":1", "\"a\":\"\\ud800\"", 1),
            "unsupported_version",
        ),
        (
            "v=2 with 1e400 in the body",
            r("\"v\":1", "\"v\":2").replacen("\"a\":1", "\"a\":1e400", 1),
            "unsupported_version",
        ),
        (
            "v=2 with a non-ASCII key",
            r("\"v\":1", "\"v\":2").replacen("\"a\":1", "\"\\u00e9\":1", 1),
            "unsupported_version",
        ),
        (
            "v=2 with an unknown top-level field",
            r("\"v\":1", "\"v\":2,\"x\":1"),
            "unsupported_version",
        ),
        (
            "v=-0 is the integer 0",
            r("\"v\":1", "\"v\":-0"),
            "unsupported_version",
        ),
        (
            "v=1.0 is the integer 1, written non-canonically",
            r("\"v\":1", "\"v\":1.0"),
            "non_canonical",
        ),
        (
            "v given twice, the last one 1",
            r("\"v\":1", "\"v\":2,\"v\":1"),
            "non_canonical",
        ),
        ("v as a string", r("\"v\":1", "\"v\":\"1\""), "malformed"),
        (
            "v=1e300 is not a safe integer",
            r("\"v\":1", "\"v\":1e300"),
            "malformed",
        ),
        (
            "v missing",
            good.replacen("\"v\":1", "", 1).replacen(",}", "}", 1),
            "malformed",
        ),
        (
            "a lone surrogate with v=1",
            r("\"a\":1", "\"a\":\"\\ud800\""),
            "malformed",
        ),
        ("an empty key", r("\"a\":1", "\"\":1"), "malformed"),
        (
            "an integer beyond u64",
            r("\"a\":1", "\"a\":99999999999999999999999"),
            "malformed",
        ),
        ("re: null", r("\"kid\"", "\"re\":null,\"kid\""), "malformed"),
        ("a top-level array", "[1]".into(), "malformed"),
        ("a byte order mark", format!("\u{feff}{good}"), "malformed"),
        ("ts=-0", r(&ts, "\"ts\":-0"), "non_canonical"),
        ("trailing whitespace", format!("{good} "), "non_canonical"),
        (
            "body keys out of order",
            r("\"a\":1", "\"b\":1,\"a\":1"),
            "non_canonical",
        ),
        (
            "a duplicated body key",
            r("\"a\":1", "\"a\":2,\"a\":1"),
            "non_canonical",
        ),
        (
            "an upper-case \\u escape",
            r("\"a\":1", "\"a\":\"\\u00E9\""),
            "non_canonical",
        ),
        (
            "an escaped slash",
            r("\"a\":1", "\"a\":\"\\/\""),
            "non_canonical",
        ),
    ];
    let mut wrong = Vec::new();
    for (about, raw, want) in &cases {
        let got = verdict(raw);
        if got != *want {
            wrong.push(format!(
                "{about}: reference says {want}, this crate says {got}"
            ));
        }
    }
    assert!(wrong.is_empty(), "\n{}", wrong.join("\n"));
}

#[test]
fn every_signature_spelling_but_the_canonical_one_is_malformed() {
    // The last of 86 base64url characters carries 2 bits of the signature and 4 unused bits, which must be zero.
    // Flipping each unused bit gives the same 64 bytes to a lenient decoder; all 15 such spellings are refused at the
    // field-format check, before the signature is even looked at. (The fixture reject-sig-padding-bits pins one.)
    let good = base_frame();
    let v: serde_json::Value = serde_json::from_str(&good).unwrap();
    let sig = v["sig"].as_str().unwrap();
    const ALPHABET: &str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let last = ALPHABET.find(&sig[85..]).unwrap();
    assert_eq!(last & 15, 0);
    for unused in 1..16 {
        let other = &ALPHABET[(last | unused)..=(last | unused)];
        let respelled = good.replace(sig, &format!("{}{other}", &sig[..85]));
        assert_eq!(verdict(&respelled), "malformed", "last character {other}");
    }
}

#[test]
fn a_correctly_signed_frame_from_the_epoch_is_stale() {
    let mut body = Body::new();
    body.insert("a".into(), 1.into());
    let draft = Draft {
        kind: "job".into(),
        id: "01M423BN0RBT69J0H0FBXEPW90".into(),
        ts: 0,
        from: "cloud".into(),
        to: device_id(),
        re: None,
        body,
    };
    assert_eq!(
        verdict(&seal(&draft, &key("cloud").signing()).unwrap()),
        "stale"
    );
}

#[test]
fn nesting_beyond_the_depth_bound_is_malformed() {
    // A documented divergence: the reference has no depth bound (a frame nested 200 deep reaches the signature
    // check there). Here the reader stops at json::MAX_DEPTH, because a Rust stack overflow aborts the process.
    let deep = format!(
        "{}{}",
        "[".repeat(json::MAX_DEPTH + 1),
        "]".repeat(json::MAX_DEPTH + 1)
    );
    let raw = base_frame().replacen("\"a\":1", &format!("\"a\":{deep}"), 1);
    assert_eq!(verdict(&raw), "malformed");
}

/// The order-* fixtures pin the order of adjacent checks. These add the non-adjacent pairs that matter most (the key
/// and the signature are both checked before the recipient) and the replay cache's rules: only accepted frames are
/// remembered, and a used id stays used whatever the body. Expectations from the reference, as above.
#[test]
fn the_check_order_holds_for_frames_wrong_in_two_ways() {
    const OTHER: &str = "dev_01M3ZGYZ00ZZZZZZZZZZZZZZZZ";
    let draft = |to: &str, ts: i64, a: i64| {
        let mut body = Body::new();
        body.insert("a".into(), a.into());
        Draft {
            kind: "job".into(),
            id: "01M423BN0RBT69J0H0FBXEPW90".into(),
            ts,
            from: "cloud".into(),
            to: to.into(),
            re: None,
            body,
        }
    };
    let cloud = key("cloud").signing();
    let fresh = NOW - 1000;
    let old = NOW - 400_000;

    let misaddressed = seal(&draft(OTHER, fresh, 1), &cloud).unwrap();
    assert_eq!(
        verdict(&misaddressed.replacen("\"a\":1", "\"a\":2", 1)),
        "bad_signature",
        "signature before recipient"
    );
    let stranger = key("attacker");
    let mut d = draft(OTHER, fresh, 1);
    d.to = OTHER.into();
    assert_eq!(
        verdict(&seal(&d, &stranger.signing()).unwrap()),
        "unknown_key",
        "key before recipient"
    );
    assert_eq!(
        verdict(&seal(&draft(OTHER, old, 1), &cloud).unwrap()),
        "wrong_recipient",
        "recipient before freshness"
    );

    // Rejected frames are not remembered: they are refused the same way every time, and do not poison the id.
    let mut v = Verifier::new(&device_id(), keyring(&["cloud"]));
    let mut code = |raw: &str| {
        v.verify(raw, NOW)
            .map_or_else(|r| r.code.as_str().to_string(), |_| "ok".into())
    };
    let stale = seal(&draft(&device_id(), old, 1), &cloud).unwrap();
    assert_eq!([code(&stale), code(&stale)], ["stale", "stale"]);
    let good = seal(&draft(&device_id(), fresh, 1), &cloud).unwrap();
    let tampered = good.replacen("\"a\":1", "\"a\":2", 1);
    assert_eq!(
        [code(&tampered), code(&tampered), code(&good), code(&good)],
        ["bad_signature", "bad_signature", "ok", "replay"]
    );
    // Replay is keyed on (from, id), not on content: a different body under a used id is still a replay.
    let reused = seal(&draft(&device_id(), fresh, 2), &cloud).unwrap();
    assert_eq!(code(&reused), "replay");
}
