//! `forgeline-agent service install|uninstall|print`: the launchd agent (macOS) or systemd user unit (Linux) that
//! keeps `forgeline-agent run` alive. Generated by the binary so the unit always names the binary that wrote it,
//! and so downstream installers can take the canonical text from `service print` instead of keeping their own copy.
//!
//! A user-level service on purpose: the daemon acts as the user (their coding agents, their repositories, their
//! Keychain) and needs no privilege beyond that.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::paths::{self, Dirs};
use crate::state::StateDir;

pub const LABEL: &str = "forgeline-agent";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    Launchd,
    Systemd,
}

impl Platform {
    pub fn current() -> Platform {
        if cfg!(target_os = "macos") {
            Platform::Launchd
        } else {
            Platform::Systemd
        }
    }

    pub fn unit_path(self, dirs: &Dirs) -> PathBuf {
        match self {
            Platform::Launchd => dirs
                .home
                .join("Library/LaunchAgents")
                .join(format!("{LABEL}.plist")),
            // $XDG_CONFIG_HOME/systemd/user: dirs.config is $XDG_CONFIG_HOME/forgeline-agent.
            Platform::Systemd => dirs
                .config
                .parent()
                .unwrap_or(&dirs.home)
                .join("systemd/user")
                .join(format!("{LABEL}.service")),
        }
    }
}

/// The environment the service runs with. launchd and systemd start services with a minimal environment, so:
/// - the XDG variables, when set, are carried over -- otherwise the daemon would look for its state somewhere
///   other than where the CLI and the hooks put it;
/// - PATH is carried over, because the actions of later phases start `claude` and `codex`, which live wherever
///   the user's shell finds them (Homebrew, mise shims, npm prefixes), not in launchd's `/usr/bin:/bin`.
pub fn service_env(get: impl Fn(&str) -> Option<String>) -> Vec<(String, String)> {
    ["PATH", "XDG_CONFIG_HOME", "XDG_STATE_HOME"]
        .iter()
        .filter_map(|k| get(k).filter(|v| !v.is_empty()).map(|v| (k.to_string(), v)))
        .collect()
}

fn xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

pub fn launchd_plist(exe: &Path, env: &[(String, String)], log: &Path) -> String {
    let mut s = String::from(concat!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
        "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n",
        "<plist version=\"1.0\">\n<dict>\n",
    ));
    let _ = writeln!(s, "  <key>Label</key>\n  <string>{LABEL}</string>");
    let _ = writeln!(
        s,
        "  <key>ProgramArguments</key>\n  <array>\n    <string>{}</string>\n    <string>run</string>\n  </array>",
        xml(&exe.to_string_lossy())
    );
    if !env.is_empty() {
        s.push_str("  <key>EnvironmentVariables</key>\n  <dict>\n");
        for (k, v) in env {
            let _ = writeln!(
                s,
                "    <key>{}</key>\n    <string>{}</string>",
                xml(k),
                xml(v)
            );
        }
        s.push_str("  </dict>\n");
    }
    // Restart on a crash or a startup error, but not after a clean exit; at most every 30 s, so a broken config
    // is a slow retry visible in the log rather than a spin.
    s.push_str("  <key>RunAtLoad</key>\n  <true/>\n");
    s.push_str("  <key>KeepAlive</key>\n  <dict>\n    <key>SuccessfulExit</key>\n    <false/>\n  </dict>\n");
    s.push_str("  <key>ThrottleInterval</key>\n  <integer>30</integer>\n");
    let log = xml(&log.to_string_lossy());
    let _ = writeln!(
        s,
        "  <key>StandardOutPath</key>\n  <string>{log}</string>\n  <key>StandardErrorPath</key>\n  <string>{log}</string>"
    );
    s.push_str("</dict>\n</plist>\n");
    s
}

// systemd unescapes C-style backslash escapes in quoted values and expands `%` specifiers everywhere.
fn systemd_quote(s: &str) -> String {
    format!(
        "\"{}\"",
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('%', "%%")
    )
}

pub fn systemd_unit(exe: &Path, env: &[(String, String)]) -> String {
    let mut s = String::from(
        "[Unit]\nDescription=forgeline-agent: hooks and typed actions for forgeline Cloud\n\n[Service]\nType=simple\n",
    );
    let _ = writeln!(s, "ExecStart={} run", systemd_quote(&exe.to_string_lossy()));
    for (k, v) in env {
        let _ = writeln!(s, "Environment={}", systemd_quote(&format!("{k}={v}")));
    }
    s.push_str("Restart=on-failure\nRestartSec=30\n\n[Install]\nWantedBy=default.target\n");
    s
}

pub fn render(
    platform: Platform,
    exe: &Path,
    env: &[(String, String)],
    state: &StateDir,
) -> String {
    match platform {
        Platform::Launchd => launchd_plist(exe, env, &state.log_dir().join("daemon.log")),
        // journald keeps a user unit's output; `journalctl --user -u forgeline-agent` reads it.
        Platform::Systemd => systemd_unit(exe, env),
    }
}

fn this_exe() -> Result<PathBuf, String> {
    let exe = std::env::current_exe()
        .and_then(fs::canonicalize)
        .map_err(|e| format!("cannot locate this binary: {e}"))?;
    Ok(exe)
}

fn env_now() -> Vec<(String, String)> {
    service_env(|k| std::env::var(k).ok())
}

fn run_cmd(program: &str, args: &[&str]) -> Result<(), String> {
    let out = Command::new(program)
        .args(args)
        .output()
        .map_err(|e| format!("{program}: {e}"))?;
    if out.status.success() {
        Ok(())
    } else {
        Err(format!(
            "{program} {}: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

/// The text `service print` shows.
pub fn print(dirs: &Dirs) -> Result<String, String> {
    Ok(render(
        Platform::current(),
        &this_exe()?,
        &env_now(),
        &StateDir::at(&dirs.state),
    ))
}

/// Write the unit and, unless `load` is false, load and start it. Returns what was done, for the user.
pub fn install(dirs: &Dirs, load: bool) -> Result<String, String> {
    let platform = Platform::current();
    let state = StateDir::open(&dirs.state).map_err(|e| e.to_string())?;
    let path = platform.unit_path(dirs);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    fs::write(&path, render(platform, &this_exe()?, &env_now(), &state))
        .map_err(|e| format!("{}: {e}", path.display()))?;
    let mut done = format!("wrote {}", path.display());
    if load {
        match platform {
            Platform::Launchd => {
                let domain = format!("gui/{}", paths::euid());
                // Replace a loaded copy, so a reinstall picks up a new binary path; "not loaded" is fine.
                let _ = run_cmd("launchctl", &["bootout", &format!("{domain}/{LABEL}")]);
                run_cmd(
                    "launchctl",
                    &["bootstrap", &domain, &path.to_string_lossy()],
                )?;
                done.push_str(&format!("; loaded it into {domain}"));
            }
            Platform::Systemd => {
                run_cmd("systemctl", &["--user", "daemon-reload"])?;
                run_cmd(
                    "systemctl",
                    &["--user", "enable", "--now", &format!("{LABEL}.service")],
                )?;
                done.push_str("; enabled and started it");
            }
        }
    }
    Ok(done)
}

pub fn uninstall(dirs: &Dirs, unload: bool) -> Result<String, String> {
    let platform = Platform::current();
    let path = platform.unit_path(dirs);
    let mut done = Vec::new();
    if unload {
        match platform {
            Platform::Launchd => {
                if run_cmd(
                    "launchctl",
                    &["bootout", &format!("gui/{}/{LABEL}", paths::euid())],
                )
                .is_ok()
                {
                    done.push("stopped and unloaded it".to_string());
                }
            }
            Platform::Systemd => {
                if run_cmd(
                    "systemctl",
                    &["--user", "disable", "--now", &format!("{LABEL}.service")],
                )
                .is_ok()
                {
                    done.push("stopped and disabled it".to_string());
                }
            }
        }
    }
    match fs::remove_file(&path) {
        Ok(()) => done.push(format!("removed {}", path.display())),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            done.push(format!("{} was not installed", path.display()))
        }
        Err(e) => return Err(format!("{}: {e}", path.display())),
    }
    if unload && platform == Platform::Systemd {
        let _ = run_cmd("systemctl", &["--user", "daemon-reload"]);
    }
    Ok(done.join("; "))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn env() -> Vec<(String, String)> {
        vec![
            ("PATH".into(), "/opt/homebrew/bin:/usr/bin".into()),
            (
                "XDG_STATE_HOME".into(),
                "/home/u/50% & <odd> \"dir\"".into(),
            ),
        ]
    }

    #[test]
    fn plist_escapes_everything_it_embeds() {
        let p = launchd_plist(
            Path::new("/Apps/a&b/forgeline-agent"),
            &env(),
            Path::new("/s/log/daemon.log"),
        );
        assert!(p.contains("<string>/Apps/a&amp;b/forgeline-agent</string>"));
        assert!(p.contains("<string>/home/u/50% &amp; &lt;odd&gt; &quot;dir&quot;</string>"));
        assert!(p.contains("<key>Label</key>\n  <string>forgeline-agent</string>"));
        assert!(!p.contains("a&b"));
    }

    #[test]
    fn systemd_unit_quotes_and_escapes_specifiers() {
        let u = systemd_unit(Path::new("/opt/my apps/forgeline-agent"), &env());
        assert!(u.contains("ExecStart=\"/opt/my apps/forgeline-agent\" run\n"));
        assert!(u.contains("Environment=\"XDG_STATE_HOME=/home/u/50%% & <odd> \\\"dir\\\"\"\n"));
        assert!(u.contains("WantedBy=default.target"));
    }

    #[test]
    fn carries_only_the_variables_the_daemon_needs() {
        let e = service_env(|k| match k {
            "PATH" => Some("/bin".into()),
            "XDG_CONFIG_HOME" => Some(String::new()),
            "HOME" => Some("/h".into()),
            _ => None,
        });
        assert_eq!(e, vec![("PATH".to_string(), "/bin".to_string())]);
    }

    #[test]
    fn unit_paths() {
        let dirs = Dirs::from_vars(|k| match k {
            "HOME" => Some("/home/u".into()),
            "XDG_CONFIG_HOME" => Some("/cfg".into()),
            _ => None,
        })
        .unwrap();
        assert_eq!(
            Platform::Launchd.unit_path(&dirs),
            PathBuf::from("/home/u/Library/LaunchAgents/forgeline-agent.plist")
        );
        assert_eq!(
            Platform::Systemd.unit_path(&dirs),
            PathBuf::from("/cfg/systemd/user/forgeline-agent.service")
        );
    }
}
