// Read the cached image_keys of the pet animations (assets/pet/keys.json, generated by
// tools/upload-pet-assets.ts).
// Read once per process; a missing file (nothing was ever uploaded) -> null, and the card degrades
// gracefully to an emoji rather than erroring.
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const KEYS_PATH = resolve(dirname(fileURLToPath(import.meta.url)), '../../assets/pet/keys.json');

let cache: Record<string, string> | null = null;
function load(): Record<string, string> {
  if (cache) return cache;
  try {
    cache = existsSync(KEYS_PATH) ? (JSON.parse(readFileSync(KEYS_PATH, 'utf8')) as Record<string, string>) : {};
  } catch {
    cache = {};
  }
  return cache;
}

// Asset name (egg/hatch/chick/bird/final) -> image_key; null when absent.
export function petImageKey(name: string): string | null {
  return load()[name] ?? null;
}
